// Throw, and Try...Catch...Finally
// The try statement defines a code block to run (to try).

// The catch statement defines a code block to handle any error.

// The finally statement defines a code block to run regardless of the result.

// The throw statement defines a custom error.

try {
    // Block of code to try
  }
  catch(err) {
    // Block of code to handle errors
  }
  finally {
    // Block of code to be executed regardless of the try / catch result
  }

//   Error Object Properties
// Property	        Description
// name	            Sets or returns an error name
// message	        Sets or returns an error message (a string)

// Error Name Values 

// Error Name	        Description
// EvalError	        An error has occurred in the eval() function
// RangeError	        A number "out of range" has occurred
// ReferenceError	    An illegal reference has occurred
// SyntaxError	        A syntax error has occurred
// TypeError	        A type error has occurred
// URIError	            An error in encodeURI() has occurred